name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Comprobar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar Jupyter y todas sus dependencias clave
      - name: Install Jupyter and dependencies
        run: |
          pip install jupyter nbformat platformdirs jupyterlab jupyter-client jupyter-console jupyter-core nbclient notebook

      # 3. Desplegar con Quarto
      - name: Deploy with Quarto
        uses: fastai/workflows/quarto-ghp@master
