name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Comprobar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar las dependencias necesarias (Jupyter, nbformat, y platformdirs)
      - name: Install Jupyter, nbformat, and platformdirs
        run: |
          pip install jupyter nbformat platformdirs

      # 3. Desplegar con Quarto
      - name: Deploy with Quarto
        uses: fastai/workflows/quarto-ghp@master
